- name: Install selinux packages
  package:
    name:
    - checkpolicy
    - policycoreutils-python

- name: Create temp directory for policy creation
  file:
    path: /etc/selinux/src/docker_log_rotate
    state: directory

- name: Copy docker_log_rotate type enforcement file
  copy:
    src: docker_log_rotate.te
    dest: /etc/selinux/src/docker_log_rotate/docker_log_rotate.te
  register: semodule_source

- name: Run checkmodule on docker_log_rotate.te
  command: /usr/bin/checkmodule -M -m -o docker_log_rotate.mod docker_log_rotate.te
  args:
    chdir: /etc/selinux/src/docker_log_rotate
  when: semodule_source.changed

- name: Build docker_log_rotate module
  command: /usr/bin/semodule_package -o docker_log_rotate.pp -m docker_log_rotate.mod
  args:
    chdir: /etc/selinux/src/docker_log_rotate
  when: semodule_source.changed

- name: Install docker_log_rotate module
  command: /usr/sbin/semodule -i docker_log_rotate.pp
  args:
    chdir: /etc/selinux/src/docker_log_rotate
  when: semodule_source.changed
